### ISSUE TITLE
Open chat on OS-notification click

### ISSUE THREAD

**Issue by coeneivan** [threefoldtech/freeflowconnect_frontend#177]

**Comment by ken-de-moor** [comment]
@coeneivan can I get some steps to reproduce this? I've never seen a OS notification for ffc before.

**Comment by coeneivan** [comment]
@ken-de-moor The first time you open ffc, you get asked by Chrome if you want to receive notifications. If you did say no, you can activate them on (see screenshot)
![image](https://user-images.githubusercontent.com/22675385/93425242-de462a80-f8b9-11ea-8f53-f1558ef6f6d3.png)

**Comment by ken-de-moor** [comment]
@coeneivan Mine are apparantly on allow, still never seen one. What triggers them?

![image](https://user-images.githubusercontent.com/59569757/93442637-5c153080-f8d0-11ea-82d8-ac57840dfa9a.png)
