### ISSUE TITLE
Android 9 Samsung galaxy a50 - Sound is being determined by a combo of media and call volume, but volume slider only changes call volume

### ISSUE THREAD

**Issue by ken-de-moor** [threefoldtech/freeflowconnect_frontend#20]
**Repro steps**
1) Join ffc on mobile with media sound muted
2) Turn on volume to max
3) Drag down default volume menu to see media volume, now drag it to max

**Expected Result**
Sound is played simply by using volume buttons

**Actual Result**
Sound is only played once media volume is also enabled

**System Info**

**Comment by MathiasDeWeerdt** [comment]
This is actually seems like correct behavior. Since we're doing a video call and videos are classified as media this is what I would expect?

**Comment by ken-de-moor** [comment]
The UX issue here is you need to actually go into advanced settings ( that are pretty well hidden ) to enable sound for our application. This is not usable for any normal user, how do other apps handle this? To this day I've always been able to just use my volume buttons at the side to mute or enable sound, it's always dynamically changed to whatever I was doing.
