### ISSUE TITLE
Room name is case sensitive, should be case insensitive

### ISSUE THREAD

**Issue by ken-de-moor** [threefoldtech/freeflowconnect_frontend#21]
**Repro steps**
1) join https://ffc.staging.jimber.org/room/Patat
2) join https://ffc.staging.jimber.org/room/patat

**Expected Result**
Joins same room

**Actual Result**
Joins different room

**System Info**

**Comment by MathiasDeWeerdt** [comment]
Since choosing a name for the room is an unfortunate byproduct of the way the room names work, it is by no means a feature and people need to use the invite links. We need case sensitivity for the uniqueness of the rooms or we would need to increase its length dramatically.

**Comment by MathiasDeWeerdt** [comment]
@coeneivan Has this been fixed yet?

**Comment by MathiasDeWeerdt** [comment]
Fixed by @coeneivan
