### ISSUE TITLE
Background removal is suddenly enabled when screensharing

### ISSUE THREAD

**Issue by ken-de-moor** [threefoldtech/freeflowconnect_frontend#213]
**Repro steps**

![image](https://user-images.githubusercontent.com/59569757/92926587-897b5d80-f43c-11ea-8e81-3fc7ad04534d.png)

2) Start screensharing

**Expected Result**
You are sharing your screen

**Actual Result**
Background removal is suddenly turned on instead of sharing the screen

![image](https://user-images.githubusercontent.com/59569757/92926643-a3b53b80-f43c-11ea-87e1-f1e102a83e38.png)

**System Info**

**Comment by coeneivan** [comment]
@ken-de-moor That's the presentation view, not the background removal
