### ISSUE TITLE
Iphone Chrome - FFC has strange broken behaviour

### ISSUE THREAD

**Issue by ken-de-moor** [threefoldtech/freeflowconnect_frontend#22]
**Repro steps**
1) Open FFC in iphone
2) Attempt to use FFC

**Expected Result**
It works the same as on android

**Actual Result**
Barely works, extremely strange behaviour where only one speaker is shown and speakers can be dragged to show the others, once each speaker is dragged it freezes everyone.
Issues:
- [x] All the video play in full-screen
- [x] Video controls visible

**System Info**

**Comment by MathiasDeWeerdt** [comment]
@KristofVanstappen @jdelrue I need an Iphone, otherwise I cannot reproduce or test this scenario.
