### ISSUE TITLE
Firefox - Firefox doesn't work on several devices

### ISSUE THREAD

**Issue by ken-de-moor** [threefoldtech/freeflowconnect_frontend#23]
**Repro steps**
1) Open ffc in firefox
2) Attempt to use it

**Expected Result**
Works on all computers

**Actual Result**
Works for some people, others report black videos and no sound

![image](https://user-images.githubusercontent.com/59569757/80630439-86b33980-8a54-11ea-89e2-fbae0aaba5f3.png)

**System Info**

**Comment by MathiasDeWeerdt** [comment]
When opening FFC in firefox I was presented with the following options
![image](https://user-images.githubusercontent.com/7256303/80687938-55c21b80-8acb-11ea-99eb-c88e0e431571.png)

When confirming these options it seems to be working like in chrome?
Whats the firefox version you're using?

**Comment by MathiasDeWeerdt** [comment]
Should be fixed
