### ISSUE TITLE
UI for mobile should be improved

### ISSUE THREAD

**Issue by JonasWijne** [threefoldtech/freeflowconnect_frontend#235]
- [x] When joining room, you should see what room name you are typing. Currently is invisible
- [x] Hide background removal
- [x] Hide screenshare
- [x] Show native share of invitation instead of link copy

**Comment by ken-de-moor** [comment]
When joining room, you should see what room name you are typing. Currently is invisible

Still happens

**Comment by ken-de-moor** [comment]
Screenshare button is still there but just doesn't work
