### ISSUE TITLE
Show an onboard "tutorial" the first time the user joins a call

### ISSUE THREAD

**Issue by coeneivan** [threefoldtech/freeflowconnect_frontend#256]
- [x] Display a message before requesting permission
- [x] Let user test intput
- [ ] Change the room joining flow to centralize and streamline all the steps
    - [ ] Central flow, not first actions in the middle and then at the bottom
    - [ ] Clear call to action where the user needs to click

**Comment by ken-de-moor** [comment]
Flow doesn't really seem to work.

![image](https://user-images.githubusercontent.com/59569757/94659097-0dba5580-0304-11eb-8087-76075738d25a.png)

Then after pressing continue it suddenly did ask me permissions
