### ISSUE TITLE
Performance on windows is bad due to GPU spiking, this also influences sound

### ISSUE THREAD

**Issue by ken-de-moor** [threefoldtech/freeflowconnect_frontend#28]
**Repro steps**
1) Do a call with several people on windows while monitoring GPU usage
2) Notice whenever sound has issues, the GPU spikes on the following proces

**Expected Result**
GPU doesn't spike when using FFC
When the GPU does spike, the audio does not break

**Actual Result**
![image](https://user-images.githubusercontent.com/59569757/81051695-7a026b80-8ec2-11ea-9f8b-158f8c6b7d2e.png)
Very laggy when this happens

**System Info**

**Comment by MathiasDeWeerdt** [comment]
Fixed.
