### ISSUE TITLE
Joining the room should be clearer.

### ISSUE THREAD

**Issue by ken-de-moor** [threefoldtech/freeflowconnect_frontend#284]
First user acceptance testing has shown an issue we haven't though of yet.

1) When you first click the join room, you get to pick a name and give permissions

2) After this you see yourself, and it seems like you're already in the room. 

We should make it clearer that the user still has to press join room after this.

**Comment by ken-de-moor** [comment]
Tagged you since you said you'd take this up together with the onboarding flow @coeneivan

**Comment by coeneivan** [comment]
Check #256
