### ISSUE TITLE
Screenshare button option is gone when window width becomes smaller

### ISSUE THREAD

**Issue by ken-de-moor** [threefoldtech/freeflowconnect_frontend#29]
**Repro steps**
1) Go to ffc, check screenshare button
2) Put the window width smaller, check screenshare button again

**Expected Result**
Screenshare button is still there

**Actual Result**
Screenshare button is gone

**System Info**

**Comment by jdelrue** [comment]
IsMobile for hiding or showing the button

OR EVEN BETTER:

Is screenshare possible? Show button

**Comment by MathiasDeWeerdt** [comment]
Fixed by @DeanVerjans
