### ISSUE TITLE
When logging out, the roomname should be pre-filled.

### ISSUE THREAD

**Issue by ken-de-moor** [threefoldtech/freeflowconnect_frontend#292]
**Repro steps**
1) Join room testken as Ken
2) Log out, change name to Ivan

**Expected Result**
Join room should be pre-filled with 'testken' same as when following an invite link

**Actual Result**
Need to enter the roomname again

**System Info**

**Comment by coeneivan** [comment]
I'm not sure this is the expected behavior.
When I log out it's because I'm done with the call.
