### ISSUE TITLE
ANDROID CHROME - when pressing back button, you leave the room, but your camera and mic is still on and everyone can still see and hear you

### ISSUE THREAD

**Issue by ken-de-moor** [threefoldtech/freeflowconnect_frontend#293]
**Repro steps**
1) Use back button at the bottom left

**Expected Result**
Left the room, back to landing room

**Actual Result**
In landing room, but everyone can still hear and see you, very dangerous if you want to run around naked

**System Info**

**Comment by ken-de-moor** [comment]
Still happens

**Comment by JonasWijne** [comment]
Problem found, this was a consiquence of choosing vue router with mode history, back button was handled as any other route change

fixed by refreshing everytime you move away form room
