### ISSUE TITLE
Emoji are "greyed out"

### ISSUE THREAD

**Issue by ken-de-moor** [threefoldtech/freeflowconnect_frontend#324]
At first I thought it was still sending and my internet was acting up.

Many other applications use this "greying out" to show that a message is not yet sent. And only showing client sided.

![image](https://user-images.githubusercontent.com/59569757/96998859-8d6ac700-1534-11eb-9e77-6fa9bb40f096.png)

VS the same emoji while highlighted.

![image](https://user-images.githubusercontent.com/59569757/96998893-9eb3d380-1534-11eb-9f56-e0120ad3b3f5.png)

**Comment by JonasWijne** [comment]
fixed in  `v3.7.1-rc01`
