### ISSUE TITLE
FFC does not work on safari

### ISSUE THREAD

**Issue by ken-de-moor** [threefoldtech/freeflowconnect_frontend#38]
**Repro steps**
1) Open FFC in Desktop Safari with people active in the room

**Expected Result**
You see everyone and can use FFC

**Actual Result**
You are the only person in the room. other people see you entered in chat.

**System Info**

**Comment by ken-de-moor** [comment]
maybe @coeneivan can help debug? @MathiasDeWeerdt  I don't have a mac myself, KVS reported the issue

**Comment by coeneivan** [comment]
Enable/disable camera&mic doesn't work

**Comment by coeneivan** [comment]
Safari can SOMETIMES join meetings

**Comment by coeneivan** [comment]
> Safari can SOMETIMES join meetings

This is fixed now by changing the codec

**Comment by coeneivan** [comment]
Disabled the unsupported functions in safari
