### ISSUE TITLE
When selecting background image and selecting a non JPG/PNG type, it is selected anyway.

### ISSUE THREAD

**Issue by ken-de-moor** [threefoldtech/freeflowconnect_frontend#40]
**Repro steps**
1) Select a png
2) Now change it to a txt
3) Press OK on the warning

**Expected Result**
The png is still listed in the input

**Actual Result**
The txt is selected

**System Info**

**Comment by coeneivan** [comment]
https://github.com/threefoldtech/freeflowconnect_frontend/pull/52

**Comment by ken-de-moor** [comment]
![image](https://user-images.githubusercontent.com/59569757/87010448-dcc7fa00-c1c6-11ea-9f6c-68f2128272a3.png)

Still happens

**Comment by coeneivan** [comment]
https://github.com/threefoldtech/freeflowconnect_frontend/pull/71
