### ISSUE TITLE
Mobile layout should work on most modern devices/browsers

### ISSUE THREAD

**Issue by ken-de-moor** [threefoldtech/freeflowconnect_frontend#50]
This is not yet to make it prettier and bug-free, for this other stories exist with creating figma designs.

For now the application should be usable for a normal user flow on the following browser/device setups.

- [x] Android Chrome
- [x] Android Firefox
- [ ] Iphone Chrome
- [x] Iphone Firefox
- [x] Iphone Safari

**Comment by ken-de-moor** [comment]
Iphone safari
----------------------
1) Join room button is entirely offscreen, had to do weird zoom shenanigangs to see it
2) After joining the camera is black and I can't see anyone else

Iphone Firefox
----------------------
Device access denied, but never got the option to give permission

Iphone Chrome
-----------------------
Device access denied, but never got the option to give permission

Android Chrome
-----------------------
Main flow works

Firefox Chrome
------------------------
Keeps spamming permission ask, never gets past this step, but I'm able to join and see the other people, not usable though.

**Comment by coeneivan** [comment]
The fact that Android firefox keeps requesting permission is because Firefox works that way :)

**Comment by ken-de-moor** [comment]
closing since issue is getting too generic, will make more seperate issues
