### ISSUE TITLE
[ANDROID CHROME] Changing video input device breaks the camera

### ISSUE THREAD

**Issue by ken-de-moor** [threefoldtech/freeflowconnect_frontend#59]
**Repro steps**
1) Join https://ffc.staging.jimber.org/room/patatt on android chrome
2) After joining, change your video device in the settings to switch between front and back cam

**Expected Result**
Camera changes

**Actual Result**
Camera freezes and stops working

**System Info**

**Comment by jdelrue** [comment]
No changing device anymore

**Comment by coeneivan** [comment]
https://github.com/threefoldtech/freeflowconnect_frontend/pull/76
