### ISSUE TITLE
[ ANDROID CHROME] Disabling camera shows part of last image

### ISSUE THREAD

**Issue by ken-de-moor** [threefoldtech/freeflowconnect_frontend#60]
**Repro steps**
1) Go on android chrome 
2) Disable camera

**Expected Result**
Camera correctly disabled and a placeholder image is shown

**Actual Result**
![image](https://user-images.githubusercontent.com/59569757/87085927-fdc53500-c230-11ea-8cc9-ae66eace8b0f.png)

**System Info**

**Comment by jdelrue** [comment]
Fix please
