### ISSUE TITLE
Disable/Enabling microphone and camera at the same time causes camera to break

### ISSUE THREAD

**Issue by ken-de-moor** [threefoldtech/freeflowconnect_frontend#62]
**Repro steps**
1) Seems to be easier to reproduce on devices with more lag, happens sometimes randomly but to force it just quickly press both camera and mic enable/disable until the camera stops updating

**Expected Result**
The camera keeps working

**Actual Result**
Camera frozen on certain image

**System Info**

**Comment by jdelrue** [comment]
Fix by adding loading anim

**Comment by coeneivan** [comment]
https://github.com/threefoldtech/freeflowconnect_frontend/pull/73
