### ISSUE TITLE
[ IPHONE SAFARI ] After logout, mic and camera were both still streaming without the user being aware

### ISSUE THREAD

**Issue by ken-de-moor** [threefoldtech/freeflowconnect_frontend#65]
**Repro steps**
1) Use Iphone Safari, enable mic and phone 
2) Log out and stay logged out

**Expected Result**
You have left the room

**Actual Result**
Camera and microphone is still playing, user has no feedback about this, a recipe for disaster

**System Info**

**Comment by coeneivan** [comment]
https://github.com/threefoldtech/freeflowconnect_frontend/pull/74
