### ISSUE TITLE
[DESKTOP SAFARI] Safari does not tell the user to use chrome, does not work correctly.

### ISSUE THREAD

**Issue by ken-de-moor** [threefoldtech/freeflowconnect_frontend#78]
**Repro steps**
1) Attempt to use safari on a mac

**Expected Result**
It should work OR Should tell the user to use google chrome instead ( Only when on a mac, not on iphone )

**Actual Result**
Does not work at all, sees no other users.

**System Info**

**Comment by coeneivan** [comment]
![image](https://user-images.githubusercontent.com/22675385/88645050-f96b9980-d0c3-11ea-8035-2faed1da8e6b.png)
I think this issue is already fixed
