### ISSUE TITLE
There should be a "No users yet" message yet when you are the only user in the room [development_invite_users]

### ISSUE THREAD

**Issue by ken-de-moor** [threefoldtech/freeflowconnect_frontend#80]
**Repro steps**
1) Go to any room without other people for example https://ffc.staging.jimber.org/room/j2qJM96hFFmvQHT

**Expected Result**
No users yet
Invite users by sending them the following link 

**Actual Result**
![image](https://user-images.githubusercontent.com/59569757/88560946-0f7b4a80-d02f-11ea-98f3-e75a2db90e29.png)

**System Info**
v2.0.0

**Comment by coeneivan** [comment]
![image](https://user-images.githubusercontent.com/22675385/89279098-452fbd00-d647-11ea-915b-d6f66bb23cd3.png)
