### ISSUE TITLE
Layout should be improved for widescreen monitors

### ISSUE THREAD

**Issue by ken-de-moor** [threefoldtech/freeflowconnect_frontend#83]
**Repro steps**
1) Go to https://ffc.staging.jimber.org/room/j2qJM96hFFmvQHT on a very wide monitor

**Expected Result**
Layout suits wider screens

**Actual Result**
Not optimal

**System Info**

**Comment by coeneivan** [comment]
@ken-de-moor @JonasWijne I don't think this is needed any more
