### ISSUE TITLE
Layout does not scale correctly, makes it impossible to join room on certain resolutions.

### ISSUE THREAD

**Issue by ken-de-moor** [threefoldtech/freeflowconnect_frontend#84]
**Repro steps**
1) Go to the join room https://ffc.staging.jimber.org/room/Patat/join

**Expected Result**
Possible to join room
Either by making it fit the screen or by adding a scrollbar

**Actual Result**
no scrollbar and no join button, impossible to join on current window size

![image](https://user-images.githubusercontent.com/59569757/88567061-405f7d80-d037-11ea-9425-ca101e1877d7.png)

**System Info**
v2.0.0

**Comment by coeneivan** [comment]
@ken-de-moor I don't think this will be an issue as this page is removed

**Comment by coeneivan** [comment]
I see this still has to be merged check #123
