### ISSUE TITLE
Camera and Microphone buttons have the wrong on/off state [development_tooltips]]

### ISSUE THREAD

**Issue by ken-de-moor** [threefoldtech/freeflowconnect_frontend#86]
**Repro steps**
1) Check the buttons

**Expected Result**
Currently both are enabled, but the buttons show they are disabled

See for same in discord when the mic is enabled
![image](https://user-images.githubusercontent.com/59569757/88567895-68031580-d038-11ea-8924-251c98982513.png)

vs disabled
![image](https://user-images.githubusercontent.com/59569757/88567913-6df8f680-d038-11ea-9a7d-e35b6fc277af.png)

**Actual Result**
![image](https://user-images.githubusercontent.com/59569757/88567847-591c6300-d038-11ea-86c2-6a47519ac0ba.png)

**System Info**
v2.0.0

**Comment by coeneivan** [comment]
The state is ok but we will implement tooltips and snackbar messages to indicate the state (or state switch).
https://github.com/threefoldtech/freeflowconnect_frontend/issues/82
