### ISSUE TITLE
It should be possible to select an image file for remove background [development_background_flickering]

### ISSUE THREAD

**Issue by ken-de-moor** [threefoldtech/freeflowconnect_frontend#87]
**Repro steps**
1) Attempt to remove background
2) Use a custom uploaded image for this

**Expected Result**
Possible to upload your own image like in previous version

**Actual Result**
Only this one is available
![image](https://user-images.githubusercontent.com/59569757/88568135-c3cd9e80-d038-11ea-9a64-6a7d7b23221d.png)

**System Info**

**Comment by ken-de-moor** [comment]
Memory leak issue at the moment

**Comment by coeneivan** [comment]
Backround keeps flikkering
