### ISSUE TITLE
It should be possible to pass username through URL

### ISSUE THREAD

**Issue by ken-de-moor** [threefoldtech/freeflowconnect_frontend#92]
This is for integration in digitalyou, where the user is already logged in from before
There should be an URL parameter that when used, skips the login flow and immediately uses their 3bot name.

**Comment by DeanVerjans** [comment]
accessible via https://ffc.staging.jimber.org/?username=Dean

**Comment by ken-de-moor** [comment]
Seems this feature was removed in v2, we will likely need it again in the future for threefold integration
