### ISSUE TITLE
Screenshare needs to be restarted every time a new user joins

### ISSUE THREAD

**Issue by ken-de-moor** [threefoldtech/freeflowconnect_frontend#94]
When user A is sharing their screen, and new users join, they do not see the shared screen.

User A currently has to stop and restart screenshare every time a new user joins.

**Comment by DeanVerjans** [comment]
When there are already two people in the room with screenshare active and a thrid one joins there wil be an error in the console: 
![image](https://user-images.githubusercontent.com/40548730/90023536-228b4d00-dcb4-11ea-872c-6705131f19a7.png)

When you refresh the page the screenshare will be working on join.

The cause of this is currently unknown.
